services:
  gateway:
    image: ${DOCKER_REGISTRY-}gateway
    build:
      context: .
      dockerfile: src/gateway/Dockerfile

  auth:
    image: ${DOCKER_REGISTRY-}auth
    build:
      context: .
      dockerfile: src/services/auth/Dockerfile


  payments:
    image: ${DOCKER_REGISTRY-}payments
    build:
      context: .
      dockerfile: src/services/payments/Dockerfile


  inventory:
    image: ${DOCKER_REGISTRY-}inventory
    build:
      context: .
      dockerfile: src/services/inventory/Dockerfile


  orders:
    image: ${DOCKER_REGISTRY-}orders
    build:
      context: .
      dockerfile: src/services/orders/Dockerfile


  notifications:
    image: ${DOCKER_REGISTRY-}notifications
    build:
      context: .
      dockerfile: src/services/notifications/Dockerfile

