services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  # sql-auth:
  #   image: mcr.microsoft.com/mssql/server:2022-latest
  #   environment:
  #     ACCEPT_EULA: "Y"
  #   env_file:
  #     - ./.secrets/sql-auth.env
  #   platform: "linux/amd64"
  #   ports:
  #     - "1433:1433"
  #   volumes:
  #     - sql-auth-data:/var/opt/mssql

  # sql-inventory:
  #   image: mcr.microsoft.com/mssql/server:2022-latest
  #   environment:
  #     ACCEPT_EULA: "Y"
  #   env_file:
  #     - ./.secrets/sql-inventory.env
  #   platform: "linux/amd64"
  #   ports:
  #     - "1434:1433"
  #   volumes:
  #     - sql-inventory-data:/var/opt/mssql

  # sql-orders:
  #   image: mcr.microsoft.com/mssql/server:2022-latest
  #   environment:
  #     ACCEPT_EULA: "Y"
  #   env_file:
  #     - ./.secrets/sql-orders.env
  #   platform: "linux/amd64"
  #   ports:
  #     - "1435:1433"
  #   volumes:
  #     - sql-orders-data:/var/opt/mssql

  # sql-payments:
  #   image: mcr.microsoft.com/mssql/server:2022-latest
  #   environment:
  #     ACCEPT_EULA: "Y"
  #   env_file:
  #     - ./.secrets/sql-payments.env
  #   platform: "linux/amd64"
  #   ports:
  #     - "1436:1433"
  #   volumes:
  #     - sql-payments-data:/var/opt/mssql

  postgres-auth:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: authdb
    env_file:
      - ./.secrets/postgres-auth.env
    ports:
      - "5432:5432"
    volumes:
      - postgres-auth-data:/var/lib/postgresql/data

  postgres-inventory:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: inventorydb
    env_file:
      - ./.secrets/postgres-inventory.env
    ports:
      - "5433:5432"
    volumes:
      - postgres-inventory-data:/var/lib/postgresql/data

  postgres-orders:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ordersdb
    env_file:
      - ./.secrets/postgres-orders.env
    ports:
      - "5434:5432"
    volumes:
      - postgres-orders-data:/var/lib/postgresql/data

  postgres-payments:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: paymentsdb
    env_file:
      - ./.secrets/postgres-payments.env
    ports:
      - "5435:5432"
    volumes:
      - postgres-payments-data:/var/lib/postgresql/data

  auth:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - RabbitMq__Host=rabbitmq
    env_file:
      - ./.secrets/auth.env
    ports:
      - "5194:8080"
    depends_on:
      - postgres-auth
      - rabbitmq

  inventory:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - RabbitMq__Host=rabbitmq
    ports:
      - "5035:8080"
    env_file:
      - ./.secrets/inventory.env
    depends_on:
      - postgres-inventory
      - rabbitmq

  orders:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - RabbitMq__Host=rabbitmq
    ports:
      - "5079:8080"
    env_file:
      - ./.secrets/orders.env
    depends_on:
      - postgres-orders
      - rabbitmq

  payments:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - RabbitMq__Host=rabbitmq
    ports:
      - "5127:8080"
    env_file:
      - ./.secrets/payments.env
    depends_on:
      - postgres-payments
      - rabbitmq

  gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ReverseProxy__Clusters__auth-cluster__Destinations__destination1__Address=http://auth:8080/
      - ReverseProxy__Clusters__inventory-cluster__Destinations__destination1__Address=http://inventory:8080/
      - ReverseProxy__Clusters__orders-cluster__Destinations__destination1__Address=http://orders:8080/
      - ReverseProxy__Clusters__payments-cluster__Destinations__destination1__Address=http://payments:8080/
    env_file:
      - ./.secrets/gateway.env
    ports:
      - "5054:8080"
    depends_on:
      - auth
      - inventory
      - orders
      - payments

  notifications:
    environment:
      - DOTNET_ENVIRONMENT=Development
      - RabbitMq__Host=rabbitmq
      - FrontendUrl=http://localhost:5173
    env_file:
      - ./.secrets/notifications.env
    depends_on:
      - rabbitmq

volumes:
  # sql-auth-data:
  # sql-inventory-data:
  # sql-orders-data:
  # sql-payments-data:
  postgres-auth-data:
  postgres-inventory-data:
  postgres-orders-data:
  postgres-payments-data:
  rabbitmq-data:
