services:
  
  sql-auth:
      image: mcr.microsoft.com/mssql/server:2022-latest
      #container_name: sql
      environment:
        ACCEPT_EULA: "Y"
      env_file:
      - ./.secrets/sql-auth.env
      # platform: "linux/amd64" for emulation on arm
      ports:
        - "1433:1433"
      volumes:
        - sql-auth-data:/var/opt/mssql
  sql-inventory:
      image: mcr.microsoft.com/mssql/server:2022-latest
      #container_name: sql
      environment:
        ACCEPT_EULA: "Y"
      env_file:
      - ./.secrets/sql-inventory.env
      # platform: "linux/amd64" for emulation on arm
      ports:
        - "1434:1433"
      volumes:
        - sql-inventory-data:/var/opt/mssql
  sql-orders:
      image: mcr.microsoft.com/mssql/server:2022-latest
      #container_name: sql
      environment:
        ACCEPT_EULA: "Y"
      env_file:
      - ./.secrets/sql-orders.env
      # platform: "linux/amd64" for emulation on arm
      ports:
        - "1435:1433"
      volumes:
        - sql-orders-data:/var/opt/mssql

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # Management UI
    # default login guest/guest (only from localhost). For other hosts use env below:
    # environment:
    #   RABBITMQ_DEFAULT_USER: teapot
    #   RABBITMQ_DEFAULT_PASS: yourpassword

volumes:
  sql-auth-data:
  sql-inventory-data:
  sql-orders-data: