// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using inventory.Data;

#nullable disable

namespace inventory.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    [Migration("20260401153100_MoveCleanedAtToProductSet")]
    partial class MoveCleanedAtToProductSet
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductTag", b =>
                {
                    b.Property<Guid>("ProductsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TagsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ProductsId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("ProductTag");
                });

            modelBuilder.Entity("inventory.Entities.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CheckedOutAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CompletionNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("DepositAmountKept")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("ReservationDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("ReservedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ReturnedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("inventory.Entities.BookingItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductSetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("ReservationDate")
                        .HasColumnType("date");

                    b.Property<string>("ReturnNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReturnedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductSetId");

                    b.ToTable("BookingItems");
                });

            modelBuilder.Entity("inventory.Entities.BookingItemComponent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookingItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("DepositValuePerUnit")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid>("SetItemId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BookingItemId");

                    b.HasIndex("SetItemId");

                    b.ToTable("BookingItemComponents");
                });

            modelBuilder.Entity("inventory.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("inventory.Entities.Photo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("inventory.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BufferDays")
                        .HasColumnType("int");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Colour")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contents")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DepositAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MaxRentalDays")
                        .HasColumnType("int");

                    b.Property<int>("MinRentalDays")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Servings")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111101"),
                            BufferDays = 1,
                            Colour = "White with rose pink",
                            Contents = "1 teapot, 6 teacups & saucers, 6 side plates, 6 cake plates, milk jug, sugar bowl, 2-tier cake stand",
                            CreatedAt = new DateTime(2025, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            DepositAmount = 80.00m,
                            Description = "A charming floral tea set perfect for an elegant afternoon. Classic bone china with a delicate rose pattern, ideal for bridal showers, baby showers, or a sophisticated catch-up with friends.",
                            IsActive = true,
                            MaxRentalDays = 2,
                            MinRentalDays = 1,
                            Name = "Vintage Rose Tea Set",
                            Price = 45.00m,
                            Servings = 6
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111102"),
                            BufferDays = 1,
                            Colour = "Cream and gold",
                            Contents = "1 teapot, 4 teacups & saucers, 4 side plates, 4 dessert plates, milk jug, sugar bowl, 3-tier stand, serving tongs",
                            CreatedAt = new DateTime(2025, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            DepositAmount = 100.00m,
                            Description = "Timeless cream and gold set that brings a touch of the Ritz to your home. Perfect for milestone birthdays, Mother's Day, or when you simply want to make an occasion feel special.",
                            IsActive = true,
                            MaxRentalDays = 2,
                            MinRentalDays = 1,
                            Name = "Classic English Afternoon Set",
                            Price = 55.00m,
                            Servings = 4
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111103"),
                            BufferDays = 1,
                            Colour = "Pastel floral",
                            Contents = "1 large teapot, 8 teacups & saucers, 8 side plates, 8 cake plates, milk jug, sugar bowl, 3-tier cake stand, cake slice, napkins (16)",
                            CreatedAt = new DateTime(2025, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            DepositAmount = 120.00m,
                            Description = "Our most popular set for larger gatherings. Pretty pastel florals on a generous three-tier stand—great for hen parties, engagement parties, or a big family Sunday.",
                            IsActive = true,
                            MaxRentalDays = 2,
                            MinRentalDays = 1,
                            Name = "Garden Party Tier Set",
                            Price = 65.00m,
                            Servings = 8
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111104"),
                            BufferDays = 1,
                            Colour = "White and grey",
                            Contents = "1 teapot, 4 teacups & saucers, 4 side plates, milk jug, sugar bowl, 2-tier stand",
                            CreatedAt = new DateTime(2025, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            DepositAmount = 70.00m,
                            Description = "Clean, modern take on high tea. Pure white ceramic with soft grey accents—ideal for contemporary homes, baby showers, or when you want a calm, uncluttered look.",
                            IsActive = true,
                            MaxRentalDays = 2,
                            MinRentalDays = 1,
                            Name = "Minimalist White Set",
                            Price = 40.00m,
                            Servings = 4
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111105"),
                            BufferDays = 1,
                            Colour = "Ivory with gold rim",
                            Contents = "1 teapot, 6 teacups & saucers, 6 side plates, 6 soup/cereal bowls, milk jug, sugar bowl, 3-tier stand, butter dish, jam pot, serving tongs",
                            CreatedAt = new DateTime(2025, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            DepositAmount = 140.00m,
                            Description = "Our most formal option. Fine bone china with a traditional border—perfect for anniversaries, retirement celebrations, or when you want to pull out all the stops.",
                            IsActive = true,
                            MaxRentalDays = 2,
                            MinRentalDays = 1,
                            Name = "Royal Style Fine China Set",
                            Price = 75.00m,
                            Servings = 6
                        });
                });

            modelBuilder.Entity("inventory.Entities.ProductSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CleanedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductSets");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222201"),
                            CreatedAt = new DateTime(2025, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Set A",
                            ProductId = new Guid("11111111-1111-1111-1111-111111111101"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222202"),
                            CreatedAt = new DateTime(2025, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Set A",
                            ProductId = new Guid("11111111-1111-1111-1111-111111111102"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222203"),
                            CreatedAt = new DateTime(2025, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Set A",
                            ProductId = new Guid("11111111-1111-1111-1111-111111111103"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222204"),
                            CreatedAt = new DateTime(2025, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Set A",
                            ProductId = new Guid("11111111-1111-1111-1111-111111111104"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222205"),
                            CreatedAt = new DateTime(2025, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Set A",
                            ProductId = new Guid("11111111-1111-1111-1111-111111111105"),
                            Status = 0
                        });
                });

            modelBuilder.Entity("inventory.Entities.ReturnAssessment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookingItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("QuantityCustomerReturned")
                        .HasColumnType("int");

                    b.Property<int>("QuantityDamaged")
                        .HasColumnType("int");

                    b.Property<int>("QuantityGood")
                        .HasColumnType("int");

                    b.Property<int>("QuantityMissing")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReplacedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SetItemId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BookingItemId");

                    b.HasIndex("SetItemId");

                    b.ToTable("ReturnAssessments");
                });

            modelBuilder.Entity("inventory.Entities.SetItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("DepositValuePerUnit")
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("SetItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333301"),
                            DepositValuePerUnit = 25.00m,
                            IsActive = true,
                            Name = "Teapot",
                            ProductId = new Guid("11111111-1111-1111-1111-111111111101"),
                            Quantity = 1
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333302"),
                            DepositValuePerUnit = 8.00m,
                            IsActive = true,
                            Name = "Teacups & Saucers",
                            ProductId = new Guid("11111111-1111-1111-1111-111111111101"),
                            Quantity = 6
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333303"),
                            DepositValuePerUnit = 7.00m,
                            IsActive = true,
                            Name = "Plates & Stand",
                            ProductId = new Guid("11111111-1111-1111-1111-111111111101"),
                            Quantity = 1
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333304"),
                            DepositValuePerUnit = 30.00m,
                            IsActive = true,
                            Name = "Teapot",
                            ProductId = new Guid("11111111-1111-1111-1111-111111111102"),
                            Quantity = 1
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333305"),
                            DepositValuePerUnit = 10.00m,
                            IsActive = true,
                            Name = "Teacups & Saucers",
                            ProductId = new Guid("11111111-1111-1111-1111-111111111102"),
                            Quantity = 4
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333306"),
                            DepositValuePerUnit = 30.00m,
                            IsActive = true,
                            Name = "Plates & Stand",
                            ProductId = new Guid("11111111-1111-1111-1111-111111111102"),
                            Quantity = 1
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333307"),
                            DepositValuePerUnit = 30.00m,
                            IsActive = true,
                            Name = "Teapot",
                            ProductId = new Guid("11111111-1111-1111-1111-111111111103"),
                            Quantity = 1
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333308"),
                            DepositValuePerUnit = 8.00m,
                            IsActive = true,
                            Name = "Teacups & Saucers",
                            ProductId = new Guid("11111111-1111-1111-1111-111111111103"),
                            Quantity = 8
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333309"),
                            DepositValuePerUnit = 26.00m,
                            IsActive = true,
                            Name = "Plates & Stand",
                            ProductId = new Guid("11111111-1111-1111-1111-111111111103"),
                            Quantity = 1
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333310"),
                            DepositValuePerUnit = 25.00m,
                            IsActive = true,
                            Name = "Teapot",
                            ProductId = new Guid("11111111-1111-1111-1111-111111111104"),
                            Quantity = 1
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333311"),
                            DepositValuePerUnit = 8.00m,
                            IsActive = true,
                            Name = "Teacups & Saucers",
                            ProductId = new Guid("11111111-1111-1111-1111-111111111104"),
                            Quantity = 4
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333312"),
                            DepositValuePerUnit = 13.00m,
                            IsActive = true,
                            Name = "Plates & Stand",
                            ProductId = new Guid("11111111-1111-1111-1111-111111111104"),
                            Quantity = 1
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333313"),
                            DepositValuePerUnit = 35.00m,
                            IsActive = true,
                            Name = "Teapot",
                            ProductId = new Guid("11111111-1111-1111-1111-111111111105"),
                            Quantity = 1
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333314"),
                            DepositValuePerUnit = 12.00m,
                            IsActive = true,
                            Name = "Teacups & Saucers",
                            ProductId = new Guid("11111111-1111-1111-1111-111111111105"),
                            Quantity = 6
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333315"),
                            DepositValuePerUnit = 33.00m,
                            IsActive = true,
                            Name = "Plates & Accessories",
                            ProductId = new Guid("11111111-1111-1111-1111-111111111105"),
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("inventory.Entities.SpareStock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("QuantityAvailable")
                        .HasColumnType("int");

                    b.Property<Guid>("SetItemId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SetItemId")
                        .IsUnique();

                    b.ToTable("SpareStocks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444401"),
                            QuantityAvailable = 2,
                            SetItemId = new Guid("33333333-3333-3333-3333-333333333301")
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444402"),
                            QuantityAvailable = 2,
                            SetItemId = new Guid("33333333-3333-3333-3333-333333333302")
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444403"),
                            QuantityAvailable = 2,
                            SetItemId = new Guid("33333333-3333-3333-3333-333333333303")
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444404"),
                            QuantityAvailable = 2,
                            SetItemId = new Guid("33333333-3333-3333-3333-333333333304")
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444405"),
                            QuantityAvailable = 2,
                            SetItemId = new Guid("33333333-3333-3333-3333-333333333305")
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444406"),
                            QuantityAvailable = 2,
                            SetItemId = new Guid("33333333-3333-3333-3333-333333333306")
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444407"),
                            QuantityAvailable = 2,
                            SetItemId = new Guid("33333333-3333-3333-3333-333333333307")
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444408"),
                            QuantityAvailable = 2,
                            SetItemId = new Guid("33333333-3333-3333-3333-333333333308")
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444409"),
                            QuantityAvailable = 2,
                            SetItemId = new Guid("33333333-3333-3333-3333-333333333309")
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444410"),
                            QuantityAvailable = 2,
                            SetItemId = new Guid("33333333-3333-3333-3333-333333333310")
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444411"),
                            QuantityAvailable = 2,
                            SetItemId = new Guid("33333333-3333-3333-3333-333333333311")
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444412"),
                            QuantityAvailable = 2,
                            SetItemId = new Guid("33333333-3333-3333-3333-333333333312")
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444413"),
                            QuantityAvailable = 2,
                            SetItemId = new Guid("33333333-3333-3333-3333-333333333313")
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444414"),
                            QuantityAvailable = 2,
                            SetItemId = new Guid("33333333-3333-3333-3333-333333333314")
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444415"),
                            QuantityAvailable = 2,
                            SetItemId = new Guid("33333333-3333-3333-3333-333333333315")
                        });
                });

            modelBuilder.Entity("inventory.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("ProductTag", b =>
                {
                    b.HasOne("inventory.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("inventory.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("inventory.Entities.BookingItem", b =>
                {
                    b.HasOne("inventory.Entities.Booking", "Booking")
                        .WithMany("BookingItems")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("inventory.Entities.Product", "Product")
                        .WithMany("BookingItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("inventory.Entities.ProductSet", "ProductSet")
                        .WithMany("BookingItems")
                        .HasForeignKey("ProductSetId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Product");

                    b.Navigation("ProductSet");
                });

            modelBuilder.Entity("inventory.Entities.BookingItemComponent", b =>
                {
                    b.HasOne("inventory.Entities.BookingItem", "BookingItem")
                        .WithMany("Components")
                        .HasForeignKey("BookingItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("inventory.Entities.SetItem", "SetItem")
                        .WithMany()
                        .HasForeignKey("SetItemId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("BookingItem");

                    b.Navigation("SetItem");
                });

            modelBuilder.Entity("inventory.Entities.Photo", b =>
                {
                    b.HasOne("inventory.Entities.Product", "Product")
                        .WithMany("Photos")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("inventory.Entities.Product", b =>
                {
                    b.HasOne("inventory.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("inventory.Entities.ProductSet", b =>
                {
                    b.HasOne("inventory.Entities.Product", "Product")
                        .WithMany("ProductSets")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("inventory.Entities.ReturnAssessment", b =>
                {
                    b.HasOne("inventory.Entities.BookingItem", "BookingItem")
                        .WithMany("ReturnAssessments")
                        .HasForeignKey("BookingItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("inventory.Entities.SetItem", "SetItem")
                        .WithMany("ReturnAssessments")
                        .HasForeignKey("SetItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BookingItem");

                    b.Navigation("SetItem");
                });

            modelBuilder.Entity("inventory.Entities.SetItem", b =>
                {
                    b.HasOne("inventory.Entities.Product", "Product")
                        .WithMany("SetItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("inventory.Entities.SpareStock", b =>
                {
                    b.HasOne("inventory.Entities.SetItem", "SetItem")
                        .WithOne("SpareStock")
                        .HasForeignKey("inventory.Entities.SpareStock", "SetItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SetItem");
                });

            modelBuilder.Entity("inventory.Entities.Booking", b =>
                {
                    b.Navigation("BookingItems");
                });

            modelBuilder.Entity("inventory.Entities.BookingItem", b =>
                {
                    b.Navigation("Components");

                    b.Navigation("ReturnAssessments");
                });

            modelBuilder.Entity("inventory.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("inventory.Entities.Product", b =>
                {
                    b.Navigation("BookingItems");

                    b.Navigation("Photos");

                    b.Navigation("ProductSets");

                    b.Navigation("SetItems");
                });

            modelBuilder.Entity("inventory.Entities.ProductSet", b =>
                {
                    b.Navigation("BookingItems");
                });

            modelBuilder.Entity("inventory.Entities.SetItem", b =>
                {
                    b.Navigation("ReturnAssessments");

                    b.Navigation("SpareStock");
                });
#pragma warning restore 612, 618
        }
    }
}
